storybook/storybook-css/vite.config.ts, storybook/storybook-react/vite.config.ts
In order to improve debugging in devtools.
=> Added sourcemap options to vite

packages/css/src/breadcrumb/breadcrumb.scss
Also, always better to prevent new network requests.
=> Quickfix chevron untill we have static route

package.json, pnpm-lock.yaml
Wait for storybook-react to be launched before launching storybook-docs, to fix local composition
=> Fix local storybook composition

.github/dependabot.yml
This PR is not so much a fix, more of a 'I hope this triggers Dependabot'. The configuration seems to be fine, I can't figure out why Dependabot stopped working.
=> Try to fix dependabot

storybook/storybook-docs/src/introduction.md
This replaces the introduction of NL Design System with an initial version of our own.
=> Update Storybook introduction

storybook/storybook-react/src/Icon/Icon.docs.mdx
We missed a mention in the docs. I couldn’t find any others.
=> Update documentation for new icon suffix

packages/css/package.json, packages/react/package.json, proprietary/assets/package.json, proprietary/react-icons/package.json, proprietary/tokens/package.json
skip-checks: true
- @amsterdam/design-system-css@0.1.8
- @amsterdam/design-system-react@0.1.8
- @amsterdam/design-system-assets@0.1.3
- @amsterdam/design-system-react-icons@0.1.8
- @amsterdam/design-system-tokens@0.1.7
=> docs(release): design system packages

storybook/storybook-docs/config/main.js, storybook/storybook-overrides.css, storybook/theme.config.js
* Styles links as in our design system
* Adds some values to the theme configuration
* Consolidates an inadvertent override in the stylesheet
=> chore: Improve Storybook theme

packages/react/src/Grid/GridCell.tsx, packages/react/src/Grid/gridCellClasses.ts, packages/react/src/Grid/index.ts, packages/react/src/Header/Header.test.tsx, packages/react/src/MegaMenu/MegaMenu.tsx, packages/react/src/MegaMenu/index.ts, packages/react/src/Overlap/Overlap.tsx, packages/react/src/Overlap/index.ts, packages/react/src/Switch/Switch.tsx, packages/react/src/Switch/index.ts
I found a few more; I think we’re complete now.
=> chore: Fix remaining type imports and exports

documentation/storybook.md, storybook/config/preview.tsx, storybook/src/components/Alert/Alert.stories.tsx, storybook/src/components/Breadcrumb/Breadcrumb.stories.tsx, storybook/src/components/Dialog/Dialog.stories.tsx, storybook/src/components/Icon/Icon.stories.tsx, storybook/src/components/OrderedList/OrderedList.stories.tsx, storybook/src/components/PageMenu/PageMenu.stories.tsx, storybook/src/components/Switch/Switch.docs.mdx, storybook/src/components/Switch/Switch.stories.tsx, storybook/src/components/UnorderedList/UnorderedList.stories.tsx
This PR removes unused keys, uses `args.children` instead of `render` when possible, removes unnecessary `React.Fragment`s, etc.
=> chore: Clean up stories

packages/react/documentation/coding-conventions.md
A small update to the docs. In the review process the second 'only' was lost, which changes the meaning of that sentence.
=> chore: Update polymorphism docs

packages/css/src/components/aspect-ratio/README.md, proprietary/tokens/src/brand/ams/proportion.tokens.json, storybook/src/components/AspectRatio/AspectRatio.stories.tsx, storybook/src/components/Card/Card.stories.tsx, storybook/src/components/Overlap/Overlap.stories.tsx
- The `2x-wide` proportion has changed from 32:9 to 16:5
- The `wide` proportion has changed from 5:4 to 4:3
- The `tall` proportion has changed from 4:5 to 3:4
=> feat: Change values for tall, wide, and extra wide aspect ratios

storybook/src/docs/developer-guide/routing-libraries.docs.mdx
Changes use of `let` to `const` in routing docs.
A user mentioned it, and immutability FTW
By changing `let` to `const`
=> chore: Update routing docs

lerna.json, package.json, pnpm-lock.yaml
It removes the Lerna dependency
We don't need it anymore, releasing is done with the Release Please GitHub action, and monorepo stuff is done with pnpm.
By using pnpm in our scripts, and uninstalling both Lerna deps. 
=> chore: Remove Lerna dependency

packages/css/src/components/switch/switch.scss
It makes sure Switch is visible in forced colors mode.
We want to support forced colors mode.
I've added a transparent border to the track and a system color to the thumb. 
=> fix: Show Switch in forced colors mode

packages/react/src/common/useKeyboardFocus.test.tsx
It adds some missing tests for the `useKeyboardFocus` hook
Part of the functionality of the hook wasn't tested, this improves that.
By writing tests 😁 
=> chore: Add some missing tests for useKeyboardFocus hook

storybook/src/components/Radio/Radio.docs.mdx, storybook/src/components/Radio/Radio.stories.tsx
Forgot to push these before merging !1460.
=> chore: Update custom radio button icon docs

storybook/src/components/Grid/Grid.stories.tsx
I forgot to commit this with #1605.
=> chore: Add whitespace around cell examples as well

package.json, packages/css/package.json, packages/react/package.json, pnpm-lock.yaml, storybook/package.json
(What changes does this PR introduce?)
(Why are these changes necessary?)
=> chore: Update minor dependencies

package.json, pnpm-lock.yaml
Attempts to resolve security vulnerabilities.
Dependabot has just reported various [vulnerabilities](https://github.com/Amsterdam/design-system/security/dependabot).
By adding overrides to the lockfile through `pnpm audit --fix`.
=> chore: Override transient dependencies to address security vulnerabilities

package.json
It removes the Volta config
We don't use it internally anymore, and we don't have any indication that it's used externally. 
By deleting the config from package.json
=> chore: Remove Volta config

.github/workflows/feature-branch-cleanup.yml, .github/workflows/feature-branch-deploy.yml
It fixes an error in our feature branch cleanup workflow. The workflow tried to access an .nvmrc file that doesn't exist in the `gh-pages` branch. 
Because our workflow was broken. 
It checks out the feature branch first, which does have the .nvmrc file. It uses it, and then checks out the `gh-pages` branch. 
=> chore: Fix feature branch cleanup workflow

packages/css/src/components/dialog/README.md
Fixes a link in the documentation
It was broken after moving docs for action group
=> fix: Broken link Dialog docs

storybook/src/foundation/assets/favicon.docs.mdx
It fixes a typo in the favicon docs.
Because the docs were incorrect.
Adding an 's'
=> chore: Fix typo in favicon docs

storybook/src/components/FieldSet/FieldSet.docs.mdx
It fixes an incorrect example in the Field Set docs.
Because it was confusing. 
By using an ErrorMessage component instead of a Paragraph. 
=> chore: Fix incorrect example in Field Set docs

.github/workflows/feature-branch-deploy.yml, .github/workflows/lint-test.yml, .github/workflows/publish.yml
It simplifies setting up a pnpm cache in our workflows.
It also removes some unnecessary properties.
This uses the recommended way to setup a pnpm cache, we don't need the workaround anymore. 
By deleting the workaround and using the recommended setup.
=> chore: Simplify setting up pnpm cache in workflows

packages/css/src/components/alert/alert.scss, packages/react/src/Alert/Alert.tsx, proprietary/tokens/src/components/ams/alert.tokens.json
1. Gives all alerts a background colour now that we have tints for it
2. Changes the colour of the informational Alert from blue to azure
3. Removes some tokens that were no longer in use
1. To make Alerts stand out more.
2. To use blue only for interactive elements
3. Because changing them didn’t do anything anyway
=> feat!: Change colours for Alert

.stylelintrc.json, package.json, packages/css/src/components/aspect-ratio/aspect-ratio.scss, packages/css/src/components/column/column.scss, packages/css/src/components/gap/gap.scss, packages/css/src/components/margin/margin.scss, packages/css/src/components/row/row.scss, packages/css/src/components/spotlight/spotlight.scss, pnpm-lock.yaml
Adds [stylelint-value-no-unknown-custom-properties](https://github.com/csstools/stylelint-value-no-unknown-custom-properties) to check if the CSS custom properties we use exist. 
We didn't check this before. A typo would be enough to have an undefined custom property.
By using [stylelint-value-no-unknown-custom-properties](https://github.com/csstools/stylelint-value-no-unknown-custom-properties), and pointing it to our built tokens file. 
=> chore: Add Stylelint plugin to check if CSS custom property exists

packages/css/src/components/tabs/tabs.scss, packages/react/src/Tabs/Tabs.test.tsx, packages/react/src/Tabs/Tabs.tsx
Removal of `tabs` aria role.
Non existent aria role causes an error.
- [] Add or update stories
=> fix(Tabs): Remove role attribute with invalid value

storybook/src/styles/docs.css
Storybook CSS override for Dialog
Display of dialog in stories was broken due to the new decorator that wraps everything in an addition div.
CSS hacks and some stylelint features disabled. These rules might not be very usefull in CSS hacks.
=> fix(docs): Display examples for Dialog correctly

storybook/package.json, storybook/src/components/Button/Button.stories.tsx, storybook/src/components/Card/Card.stories.tsx, storybook/src/components/Footer/Footer.stories.tsx, storybook/src/components/Icon/Icon.stories.tsx, storybook/src/components/OrderedList/OrderedList.stories.tsx, storybook/src/pages/amsterdam/ArticlePage/ArticleHeader.tsx, storybook/src/pages/amsterdam/FormPage/FormPage.tsx, storybook/src/pages/amsterdam/HomePage/HomeSpotlight.tsx, storybook/src/pages/amsterdam/HomePage/HomeTopTasks.tsx, tsconfig.json
It adds a type check for Storybook to our `lint` script.
Stories should be type checked as well.
Adding a `lint` script to our Storybook package and fixing the resulting errors. 
=> chore: Add Storybook type check

proprietary/tokens/README.md
It adds docs on 'default' key filter in design tokens.
We did not document that we do this yet. 
With my AI writing buddy.
=> chore: Add docs on ‘default’ key filter in tokens

storybook/src/foundation/design-tokens/space.docs.mdx
Fix typo in Space design tokens docs
Wrong values
Rewrite
=> chore: Fix typo in Space design tokens docs

storybook/src/pages/amsterdam/common/AppHeader.tsx, storybook/src/pages/amsterdam/common/menu.ts
This implements the Mega Menu in our example pages.
=> chore(docs): Add mega menu to example pages

.github/workflows/feature-branch-deploy.yml, .github/workflows/lint-test.yml, .github/workflows/publish.yml, CONTRIBUTING.md, package.json
It runs a `postinstall` script which builds our packages. I've updated our workflows as well, to simplify them a bit. 
We often forget to run `build` after `install`, this makes sure that's not an issue anymore. 
By adding a `postinstall` script and by only building storybook when we need to. 
- We can check if `lint-test` and feature branch workflows work in this PR, but I'm not sure if this'll break the `publish` workflow. That's a bit harder to test.
=> chore: Build packages post install, simplify workflows

package.json
Upgrade required version of PNPM via corepack.
To stay up-to-date with the most recent stable version of PNPM.
By upping PNPM value in `engines` to 10 and by upgrade PNPM via the CLI:
```
corepack use pnpm@latest
```
The changes were tested by running
```
pnpm clean && pnpm install && pnpm start
```
and then checking out several pages and components in Storybook.
=> feat(deps)!: Require PNPM 10.4.1

packages/css/src/components/icon/README.md, storybook/src/components/IconButton/IconButton.docs.mdx, storybook/src/components/Link/Link.docs.mdx, storybook/src/components/LinkList/LinkList.docs.mdx, storybook/src/docs/developer-guide/interactivity.docs.mdx, storybook/src/foundation/design-tokens/text.docs.mdx
- Uses new names in the docs for the `color` prop of Icon Button, Link and Link List Link.
- Completes these lists by adding missing colours.
- Removes the link to Stijlweb where some backgrounds allow multiple foreground colours, but different for body text and headings. We prescribe a single foreground colour per background.
- Uses British English spelling in places where we didn’t.
Improves the description of our current stance on foreground colours.
n/a
- n/a
=> chore(docs): Update instructions for contrast and inverse colour

packages/css/src/components/heading/heading.scss, packages/react/src/Header/Header.tsx, packages/react/src/Heading/Heading.test.tsx, packages/react/src/Heading/Heading.tsx
Changes the class names from `ams-heading--level-x` to `ams-heading--x`.
We never include the name of the variation in our classes and tokens, only the values. We also just removed ‘level’ from the names of the typography tokens.
n/a
- n/a
=> fix(Heading)!: Remove ‘level’ from class name

packages/react/src/Heading/Heading.tsx
=> chore(Heading): Rename internal variable once more

storybook/src/components/Header/Header.stories.tsx, storybook/src/pages/amsterdam/common/AppHeader.tsx
Change the Headings in the mega menu examples to `h3`.
Our Header has a hidden `h2` in the navigation section. The following Headings that are part of the navigation section should be `h3`.
n/a
=> chore(Header): Change Headings in mega menu examples to level 3

package.json, pnpm-lock.yaml
It fixes 2 Dependabot alerts.
Vulnerabilities are bad.
We don't use these dependencies directly, so I've had to use `overrides` in our `package.json`.
=> chore: Fix Dependabot alerts

storybook/src/brand/design-tokens/space.docs.mdx, storybook/src/brand/design-tokens/typography.docs.mdx, storybook/src/styles/docs.css
Removed some fluff from these docs.
- Remove these unreadable clamps, just show pixels
- More visual examples
- Shorter texts
- Less explaining our design choices
To increase their usability.
n/a
- n/a
=> chore(docs): Simplify documentation of Space and Typography tokens

.github/workflows/publish.yml
It fixes the Storybook deploy on publish. 
It's broken.
In a previous setup, we used a different folder structure. I forgot to change it. 
=> chore: Fix Storybook deploy

.github/workflows/publish.yml
Reverts temporary changes to Publish workflow. 
We needed the temporary changes to force a Storybook deploy. That's done, so we can revert the changes. 
Uncommenting. 
=> chore: Revert temporary changes to Publish workflow

pnpm-lock.yaml, proprietary/react-icons/package.json
Allows installing our react-icons package in a React 19 application.
We forgot this package in #1857.
- n/a
=> feat(deps): Indicate support for React 19 applications

storybook/config/preview.tsx, storybook/src/components/Grid/Grid.stories.tsx
Sorts the props of a component in the `<Controls>` Doc Block.
This can be tested on Grid and Dialog. Before, required props or props that we gave an initial value in `args` were sorted before the others.
It also fixes a misplaced configuration setting for the backgrounds feature.
We only sorted them in the Controls addon. Apparently, the doc block must be configured [separately](https://github.com/storybookjs/storybook/issues/25386#issuecomment-1905468177).
n/a
- n/a
=> chore(docs): Sort props in controls doc block

packages/react/src/Image/Image.tsx
Omits the `children` prop from `HTMLImageElement` in our `Image` component.
`HTMLImageElement` extends `HTMLElement`, but we see no need for child elements in our images. We ran into this in #1972.
n/a
- n/a
=> fix(Image)!: Remove children prop

packages-proprietary/tokens/src/components/ams/page-footer.tokens.json, packages/css/src/components/page-footer/page-footer.scss
It sets the correct inline padding for the Footer menu. 
We forgot these when changing Grid.
Copy what was happening in Grid. 
=> fix(PageFooter): Set correct inline padding

proprietary/tokens/src/components/ams/page.tokens.json
Removes a legacy token directory
We probably added this by accident
Delete
=> chore: Remove legacy token directory

packages-proprietary/tokens/src/components/ams/card.tokens.json
Updates values for spacing tokens of Card.
This is a follow-up for #1972, hence the ‘chore’ prefix – this doesn’t need to go into the change log.
We want:
- No extra space between the Heading and the following Paragraph
- XS space between a tagline (metadata) and the Heading
- S space below the image
Visually, together with @Bondt007.
- n/a
=> chore(Card): Improve whitespace

CONTRIBUTING.md, packages-proprietary/assets/LICENSE.md, packages-proprietary/assets/font/LICENSE.md, packages-proprietary/react-icons/LICENSE.md, packages-proprietary/tokens/LICENSE.md
- Writes the word ‘proprietary’ correctly
- Updates the spelling of ‘license’ to British English, except in actual license headers
- Adds a dash between ‘open source’ if it is used as an adjective 
To show that we can spell things corretcly.
n/a
- n/a
=> chore: Fix typos in licences and licence docs

.github/workflows/feature-branch-cleanup.yml, .github/workflows/feature-branch-deploy.yml, .github/workflows/lint-test.yml, .github/workflows/publish.yml
It adds permissions to our workflows.
We received some [code scanning alerts](https://github.com/Amsterdam/design-system/security/code-scanning/1). By default, workflows have full access, which doesn't adhere to the principle of least privilege. This PR adds the necessary permissions for each workflow, which means full access is revoked.
By adding the permissions to the workflow files. I've tested the workflows in [this fork](https://github.com/alimpens/design-system). Everything seems to work as expected, with one exception: I couldn't test publishing the packages to NPM, because [npmjs.com](https://www.npmjs.com/) was having log-in issues. If we have issues on our next publish, this …
=> chore: Add permissions to workflows

packages/css/src/components/radio/radio.scss
It adds some missing styling for forced colors mode. 
We recently changed the Radio styling, but forgot forced colors mode. 
Adding 2 style rules.
=> fix(Radio): Add missing forced colors styling

packages/react/src/PageHeader/PageHeader.test.tsx, packages/react/src/PageHeader/PageHeader.tsx, storybook/src/components/Header/PageHeader.docs.mdx, storybook/src/components/Pagination/Pagination.docs.mdx
It allows users to use a custom link component for the logo link.
So users can use their applications's routing solution.
Add a prop called `logoLinkComponent` with a default, and use that to render the logo link. 
I've tested this in our prototypes.
=> feat(Page Header): Allow a custom link component for the logo link

packages-proprietary/assets/README.md
Update docs
Betterer
Change text
=> chore: Update Assets README

packages-proprietary/assets/README.md, packages-proprietary/tokens/README.md, packages/css/README.md
Updates the README for the CSS, assets and tokens packages.
Some things were out-of-date or incorrect. 
Typing.
=> chore: Update README for CSS, assets and tokens packages

storybook/src/components/TextInput/TextInput.docs.mdx
Updates the Text Input docs. 
There was a typo and a guideline that is irrelevant for numbers. 
Typing
=> chore: Update Text Input docs

storybook/src/components/DateInput/DateInput.docs.mdx, storybook/src/components/DateInput/DateInput.stories.tsx
It adds documentation on asking for easy to remember or find dates.
We previously only offered our Date Input component, which is not the best way to ask for these kinds of dates.
Adding stories and writing docs. Mostly based on [this gov.uk documentation](https://design-system.service.gov.uk/components/date-input/).
=> chore(Date Input): Document asking for easy to remember or find dates

package.json, packages-proprietary/tokens/package.json, pnpm-lock.yaml
- Updates `@eslint/markdown` to [version 7](https://github.com/eslint/markdown/releases/tag/v7.0.0) (major) to get `@eslint/plugin-kit` 0.3.3+ downstream
- Updates `wait-on` to get `form-data` 4.0.4 downstream
- Updates other packages with new minor releases
- Updates `style-dictionary` to [version 5](https://github.com/style-dictionary/style-dictionary/releases/tag/v5.0.0) (major)
The breaking changes for the two major updates don’t seem to affect us.
The first two resolve the [2 security issues](https://github.com/Amsterdam/design-system/security/dependabot) we currently have. The others are a bonus.
n/a
Before submitting your pull request, please ensure you have done the following. …
=> chore: Update @eslint/markdown and style-dictionary to new major versions

.github/workflows/feature-branch-cleanup.yml
It installs pnpm in our clean up workflow. 
[This update](https://github.com/Amsterdam/design-system/pull/2195) made caching automatic when there's a valid `packageManager` field is present in your `package.json`. That is the case for us, but we did not install pnpm in the clean up workflow, which is necessary for package manager caching. 
Copy pasta from feature branch deploy workflow. 
=> chore: Install pnpm in clean up workflow

packages/react/package.json, packages/react/tsconfig.build.json, packages/react/tsconfig.test.json
It excludes test files from our published React package.
It isn't necessary to publish our tests files. 
Added a separate build tsconfig, which extends the regular one and only excludes the test files. Also removed the test tsconfig, that didn't really serve a purpose.
=> chore: Exclude test files from published package

packages/react/src/Heading/Heading.tsx, packages/react/src/Icon/Icon.tsx, packages/react/src/Paragraph/Paragraph.tsx, packages/react/src/Table/TableCaption.tsx
Some duplicate copyright notices ended up in our codebase, this removes them. 
Duplicate = bad
Searched for
```
*/
/*
```
to find them and deleted them. 
=> chore: Remove duplicate copyright notices

storybook/src/brand/design-tokens/inputs.docs.mdx, storybook/src/brand/design-tokens/links.docs.mdx
This adds documentation for recently added common input tokens.
So people know that they exist and how to use them.
n/a
- n/a
=> chore(Tokens): Add documentation for recently added common input tokens
