Amsterdam/design-system

packages/css/src/top-task-link/README.md
packages/css/src/top-task-link/top-task-link.scss
packages/react/src/TopTaskLink/README.md
packages/react/src/TopTaskLink/TopTaskLink.test.tsx
packages/react/src/TopTaskLink/TopTaskLink.tsx
packages/react/src/TopTaskLink/index.ts
packages/react/src/index.ts
packages/react/src/unstyled/index.ts
proprietary/tokens/src/components/amsterdam/top-task-link.tokens.json
storybook/storybook-react/src/components/TopTaskLink/TopTaskLink.docs.mdx
storybook/storybook-react/src/components/TopTaskLink/TopTaskLink.stories.tsx

To discuss:
- currently, when you select the toptask with a screenreader, it reads 'link title, link description', implying there are 2 links when there's only one. I think we should change the structure to match https://inclusive-components.design/cards/ -> we've changed it to two `span`s, which makes a screenreader read it as one. Also, we've added an `aria-label` with `${label}, ${description}`
- should you be able to add an icon in the mvp? -> not mvp
- do we want to cut off the title and description at 2 lines in the component? [Like so](https://gitlab.com/os-amsterdam/website-onderzoek-en-statistiek/-/blob/develop/website/components/Card/Card.style.js?ref_type=heads#L100-105) -> Vincent will check with Inge

Add toptask link

---

packages/css/src/breadcrumb/breadcrumb.scss
packages/css/src/checkbox/checkbox.scss
packages/css/src/link/link.scss

A couple of changes in this PR:
- I've remove the padding from standalone and in list links, checkboxes and breadcrumbs. [The new WCAG states that hit areas only have to be 24x24px](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html), so the padding isn't necessary.
- I've fixed a typo in a token reference
- I've changed the display for standalone link to `inline-block`, so the hit area is the same as the line-height.

Remove padding from links and some other improvements

---

packages/css/src/index.scss
packages/css/src/page-menu/README.md
packages/css/src/page-menu/page-menu.scss
packages/react/src/PageMenu/PageMenu.test.tsx
packages/react/src/PageMenu/PageMenu.tsx
packages/react/src/PageMenu/README.md
packages/react/src/PageMenu/index.ts
packages/react/src/index.ts
packages/react/src/unstyled/index.ts
proprietary/tokens/src/components/amsterdam/page-menu.tokens.json
storybook/storybook-react/src/components/PageMenu/PageMenu.docs.mdx
storybook/storybook-react/src/components/PageMenu/PageMenu.stories.tsx

In order te re-use the horizontal menu in both the Header and Footer paterns we could use something like this. I've kept the amount of props like text labels or icons to a minimum.

Add PageMenu Component

---

proprietary/tokens/src/brand/amsterdam/typography.tokens.json

Projects using  postcss-safe-parser  (like CRA 4) are getting a build error on the :root variables that use a calc function without `calc()`.

Wrap calculations in clamp css values in calc()

---

packages/css/src/accordion/accordion.scss
packages/css/src/alert/alert.scss
packages/css/src/blockquote/blockquote.scss
packages/css/src/breadcrumb/breadcrumb.scss
packages/css/src/button/button.scss
packages/css/src/checkbox/checkbox.scss
packages/css/src/form-label/form-label.scss
packages/css/src/heading/heading.scss
packages/css/src/link/link.scss
packages/css/src/page-heading/page-heading.scss

This reset prevents adjustments of font size after orientation changes in iOS. We added it here and there, but not to all typography elements

Consistently add reset to all typography elements

---

packages/react/src/Screen/Screen.tsx

> The default value of `lang` is unknown, therefore it is recommended to always specify this attribute with the appropriate value. ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang))
Adding this to the `Screen` component is appropriate as it’s the outermost component we have control over and it applies to the entire tree (“If these attributes are omitted from an element, then the language of this element is the same as the language of its parent element, if any” – [Spec](https://html.spec.whatwg.org/multipage/dom.html#attr-lang))
Support for more languages through a prop with a number of options may follow – see https://amsterdam.nl/stijlweb/heldere-taal/engels-talen/.

Set screen language to Dutch

---

packages/react/src/Accordion/Accordion.test.tsx
packages/react/src/Accordion/AccordionSection.test.tsx
packages/react/src/Accordion/useFocusWithArrow.test.tsx
packages/react/src/Accordion/useFocusWithArrows.tsx
packages/react/src/Alert/Alert.test.tsx
packages/react/src/AspectRatio/AspectRatio.test.tsx
packages/react/src/Blockquote/Blockquote.test.tsx
packages/react/src/Card/Card.test.tsx
packages/react/src/Checkbox/Checkbox.test.tsx
packages/react/src/Footer/Footer.test.tsx
packages/react/src/FormLabel/FormLabel.test.tsx
packages/react/src/Grid/Grid.test.tsx
packages/react/src/Grid/GridCell.test.tsx
packages/react/src/Heading/Heading.test.tsx
packages/react/src/Highlight/Highlight.test.tsx
packages/react/src/Icon/Icon.test.tsx
packages/react/src/Link/Link.test.tsx
packages/react/src/OrderedList/OrderedList.test.tsx
packages/react/src/PageHeading/PageHeading.test.tsx
packages/react/src/PageMenu/PageMenu.test.tsx
packages/react/src/Paragraph/Paragraph.test.tsx
packages/react/src/Screen/Screen.test.tsx
packages/react/src/TopTaskLink/TopTaskLink.test.tsx
packages/react/src/UnorderedList/UnorderedList.test.tsx
packages/react/src/VisuallyHidden/VisuallyHidden.test.tsx
plop-templates/react.test.tsx.hbs

Improve test descriptions

---

storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
storybook/storybook-react/src/Card/Card.stories.tsx
storybook/storybook-react/src/Grid/Grid.stories.tsx
storybook/storybook-react/src/Image/Image.stories.tsx

Found some nice numbers again, this time for our 16:9 and 5:4 aspect ratios.
Smaller images suffice – less download time, same result, no max widths necessary.

Simplify image sizes in docs

---

packages/css/src/aspect-ratio/README.md
packages/css/src/aspect-ratio/aspect-ratio.scss
packages/css/src/screen/screen.scss
packages/react/src/AspectRatio/AspectRatio.test.tsx
packages/react/src/AspectRatio/AspectRatio.tsx
packages/react/src/Screen/Screen.test.tsx
packages/react/src/Screen/Screen.tsx
proprietary/tokens/src/brand/amsterdam/proportion.tokens.json
proprietary/tokens/src/components/amsterdam/aspect-ratio.tokens.json
proprietary/tokens/src/components/amsterdam/screen.tokens.json
storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
storybook/storybook-react/src/Screen/Screen.stories.tsx

This prepares for a `2x-wide` aspect ratio rather than an `extra-extra-wide` one and is generally easier to read.

Shorten ‘extra’ prefix to ‘x’

---

packages/css/src/top-task-link/README.md
packages/react/src/TopTaskLink/TopTaskLink.test.tsx
packages/react/src/TopTaskLink/TopTaskLink.tsx
storybook/storybook-react/src/TopTaskLink/TopTaskLink.docs.mdx
storybook/storybook-react/src/TopTaskLink/TopTaskLink.stories.tsx

Decided with the designers. A Top Task Link without a description defeats the purpose - a link to a top task always needs more context. It also looks too much like a regular link otherwise. For a group of links without a description we use the link list.

Require description  for top task link

---

packages/css/src/footer/footer.scss
packages/css/src/grid/grid.scss
packages/css/src/highlight/highlight.scss
packages/react/src/Grid/Grid.test.tsx
packages/react/src/Grid/Grid.tsx
packages/react/src/Grid/GridCell.tsx
proprietary/tokens/src/components/amsterdam/grid.tokens.json
proprietary/tokens/src/components/amsterdam/highlight.tokens.json
storybook/storybook-docs/src/grid.stories.mdx
storybook/storybook-react/src/Grid/Grid.docs.mdx
storybook/storybook-react/src/Grid/Grid.stories.tsx
storybook/storybook-react/src/GridCell/GridCell.docs.mdx
storybook/storybook-react/src/shared/argTypes.ts

* Add padding classes
* Rename padding to space and use margin
* Use padding again because of collapsing margins
* Allow start alignment of screen
* Remove explicit horizontal centring of grid
* Implement dense grid
* Add documentation
* Make spacing a local prop for Grid for now
* Document vertical spacing
* Rename ‘space’ to ‘margin’
* Finish rename
* Prevent using vertical margin together with top or bottom
* Update design documentation
* Remove unnecessary test
* Halve the number of margin classes with local custom properties
* Add compact story and a control for density
* Revert "Allow start alignment of screen"
This reverts commit b09357d45d0e58381df150f93520ade6aa318645.
* Improve documentation and story controls
* Capitalise column headers
* Rename ‘margin’ to ‘padding’
* Remove …

Add compact grid (#758)

---

storybook/storybook-react/config/viewports.ts

We’re simplifying the list of viewports in Storybook with which people can get an indication of how a component will work on a phone, tablet or desktop computer.
Our responsive framework is ready to serve any screen resolution, but we’re not going to design every component or screen in every one of them. Our designers are used to making high-fidelity designs in Figma and need some control over the width of the frames they create and the measurements of our layout and typography at these widths.
We have decided to go with 320, 832 and 1600 as reference widths for design. It seems logical to match that list in Storybook. I tried to find logical heights to match.

Simplify viewports in Storybook

---

proprietary/tokens/src/components/amsterdam/grid.tokens.json

Hee Chan reported that this grid CSS breaks the CRA build. This was previously the case in typography.
Since the old CRA (v4) uses a buggy safe css parser, it does not accept "unsafe" calculations. It needs to be used with `calc()`. Same issue with the Typography.

This breaks the (old) CRA builds

---

LICENSE.md
storybook/storybook-overrides.css

- Double class selector instead of !important
- Stricter use of direct child selectors
- Add usage of .sb-unstyled class
- Font size slightly smaller again
I am aware that this is a tricky approach. Have tested all pages visually now. I want this to work; it greatly improves the design and usability of our Storybook. At the same time, I’m ready to remove the stylesheet altogether if we keep finding issues.

chore: Tighten Storybook style overrides

---

packages/react/src/Link/Link.tsx
proprietary/tokens/src/components/amsterdam/link.tokens.json
storybook/storybook-docs/src/typography.stories.mdx

Neither Inge nor I knew why links in lists had a smaller font size. We agree that all three paragraph sizes must be available for link lists as well. For now, setting the regular font size (level 6) to links is enough.

fix: Apply regular font size to lists of links

---

packages/react/src/Grid/GridCell.test.tsx
packages/react/src/Grid/GridCell.tsx
packages/react/src/Spotlight/Spotlight.test.tsx
packages/react/src/Spotlight/Spotlight.tsx
storybook/storybook-react/src/Grid/Grid.docs.mdx
storybook/storybook-react/src/Grid/Grid.stories.tsx
storybook/storybook-react/src/Spotlight/Spotlight.docs.mdx
storybook/storybook-react/src/Spotlight/Spotlight.stories.tsx

And update the approach on ‘Spotlight’.

feat: Allow ‘Grid Cell’ to render a custom HTML element

---

packages/react/package.json
pnpm-lock.yaml
storybook/storybook-react/package.json

We’re not using this.
@hcvdhaar Did I forget why we added this in the first place?

chore: Remove unused date-fns package

---

CONTRIBUTING.md
package.json
pnpm-lock.yaml
storybook/storybook-docs/package.json
storybook/storybook-react/package.json

This removes an unused dependency and uses `start` to start Storybook, instead of `storybook`

chore: Remove unused dependency and simplify scripts

---

packages/css/src/components/grid/README.md

We apparently forgot this one when renaming to ‘Spotlight’.

chore: Fix mention of ‘Higlight’ in grid docs

---

proprietary/tokens/src/brand/amsterdam/color.tokens.json

This has been removed from Figma a couple of weeks ago. We don’t use it anywhere, and chances are slim that anyone else does.

fix!: Remove unused grey-4 color token

---

packages/css/src/components/spotlight/spotlight.scss
packages/react/src/Footer/FooterTop.tsx
packages/react/src/Spotlight/Spotlight.test.tsx
packages/react/src/Spotlight/Spotlight.tsx
proprietary/tokens/src/components/amsterdam/spotlight.tokens.json
storybook/storybook-react/src/Spotlight/Spotlight.docs.mdx
storybook/storybook-react/src/Spotlight/Spotlight.stories.tsx

This renames `light-blue` to `blue` and `blue` to `dark-blue` and sorts all lists alphabetically.

feat!: Change blue color names of Spotlight to match Badge API

---

.release-please-manifest.json

We released new versions of `assets` and `react-icons` which we didn't specify in the release please manifest.
This PR fixes that

fix: Sync release please version numbers to released versions

---

release-please-config.json

The last release wasn't completely handled by Release Please, so it doesn't quite know when to stop looking for commit messages to add to the changelogs. This PR sets the bootstrap SHA to the latest released commit to fix that.
After a release has been completely handled by Release Please, we can remove this line from the config.

chore: Update release please bootstrap SHA

---

packages/css/src/components/button/README.md
storybook/src/components/Button/Button.docs.mdx
storybook/src/components/Button/Button.stories.tsx

I added this story a couple of days ago while working on padding. It shows the effect of vertical padding and line height in action simultaneously (it seems like line height could be a bit smaller here), and it prepares a case against the potential claim that “button labels don’t wrap.”

chore: Add example of wrapping button label

---

proprietary/tokens/src/brand/amsterdam/space.compact.tokens.json
proprietary/tokens/src/brand/amsterdam/space.tokens.json
proprietary/tokens/src/components/amsterdam/column.tokens.json
proprietary/tokens/src/components/amsterdam/gap.tokens.json
proprietary/tokens/src/components/amsterdam/grid.compact.tokens.json
proprietary/tokens/src/components/amsterdam/grid.tokens.json
proprietary/tokens/src/components/amsterdam/header.tokens.json
proprietary/tokens/src/components/amsterdam/margin.tokens.json
proprietary/tokens/src/components/amsterdam/mega-menu.tokens.json

The ‘Grid Space’ name and `amsterdam.space.grid` namespace seem fine, although it may be unfortunate to name it after one component that uses it, even if it is the main one. An alternative can be ‘Layout Space’ and `amsterdam.space.layout`, which match the name of the group of components Grid belongs to.

feat!: Group design tokens for Grid Space

---

packages/css/src/components/header/header.scss
packages/react/src/Header/Header.tsx
proprietary/tokens/src/components/amsterdam/header.tokens.json

I came across this mistake, where `Header` uses a token of `Link`.

feat!: Rename ‘header logo’ to ‘header logo link’ and add missing token for outline offset

---

packages/css/src/components/button/button.scss
packages/react/src/Button/Button.test.tsx
packages/react/src/Button/Button.tsx
proprietary/tokens/src/components/amsterdam/button.tokens.json
storybook/src/components/Button/Button.stories.tsx

Removed busy state (the aria state did not apply to a button)
Added `className` prop

fix: Button fixes

---

.github/workflows/feature-branch-cleanup.yml
.github/workflows/publish.yml
documentation/publishing.md
release-please-config.json

- Removed `group-pull-request-title-pattern`, because this caused an error in the pipeline, which aborts the action
- Changed the condition for publication. [The condition in the docs](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#automating-publication-to-npm) doesn't work (anymore)
- Do not try to clean a feature branch deploy on closed PRs with `main` as the base, because `main` doesn't have feature branch deploys

chore: Fix release pipeline

---

proprietary/tokens/src/brand/amsterdam/space.tokens.json

I guess mishandling a merge conflict resulted in these incorrect values.

fix: Fix small space token lengths

---

package.json

This allows [Volta](https://volta.sh) users to automatically use the appropriate versions of node and npm.

chore: Add Volta tooling versions

---

packages/css/src/components/screen/screen.scss
packages/react/src/Screen/Screen.tsx
proprietary/tokens/src/components/ams/screen.tokens.json

The initial value for `background-color` is `transparent`. I can imagine either dark mode or an OS or browser theme setting a background colour, but I’d rather be sure it’s white. We can adapt for dark mode later.
Another reason to define it explicitly is that even though a white background may come by default sometimes, it is an explicit part of our design that other components rely on.
We need the `100vh` height for applications, e.g. to accommodate the side menu. We also need it to ensure the white background spans from top to bottom.

feat: Add background colour and full-height prop to Screen

---

packages/css/src/components/accordion/accordion.scss
packages/css/src/components/button/button.scss
packages/css/src/components/checkbox/checkbox.scss
packages/css/src/components/fieldset/fieldset.scss
packages/css/src/components/radio/radio.scss
packages/css/src/components/search-field/search-field.scss
packages/css/src/components/text-area/text-area.scss
packages/css/src/components/text-input/text-input.scss
proprietary/tokens/src/brand/ams/border.tokens.json
proprietary/tokens/src/common/ams/border.tokens.json
proprietary/tokens/src/common/ams/link-appearance.tokens.json
proprietary/tokens/src/components/ams/accordion.tokens.json
proprietary/tokens/src/components/ams/alert.tokens.json
proprietary/tokens/src/components/ams/button.tokens.json
proprietary/tokens/src/components/ams/checkbox.tokens.json
proprietary/tokens/src/components/ams/radio.tokens.json
proprietary/tokens/src/components/ams/search-field.tokens.json
proprietary/tokens/src/components/ams/table.tokens.json
proprietary/tokens/src/components/ams/tabs.tokens.json
proprietary/tokens/src/components/ams/text-area.tokens.json
proprietary/tokens/src/components/ams/text-input.tokens.json
storybook/src/docs/borders.docs.mdx

- I moved the border tokens from `common` to `brand`, they make more sense there imo
- Negative values don't seem to work with these tokens, so [Tabs button still has a negative hardcoded value](https://github.com/Amsterdam/design-system/compare/feat/DES-578-border-tokens?expand=1#diff-64509d5294e86b2b12c8e2cb3deb74ddeb8654eb63a09bd25743a5d8e307f9edR21)
- In Table, the border is set on the cell, because a border on the row doesn't work with the default `border-collapse: separate`. `border-collapse: collapse` caused other issues I think, but I can't quite remember what they were.

feat: Add border tokens and use rems for widths

---

.github/dependabot.yml

Dependabot currently isn't working correctly in our repo. This has happened before, changing the check interval was enough then to fix it. Hopefully this will start dependabot up again.

chore: Change dependabot check frequency to restart it

---

packages/css/src/components/search-field/search-field.scss
packages/css/src/components/text-area/text-area.scss
packages/css/src/components/text-input/text-input.scss
proprietary/tokens/src/components/ams/search-field.tokens.json
proprietary/tokens/src/components/ams/text-area.tokens.json
proprietary/tokens/src/components/ams/text-input.tokens.json

While reviewing #1152, I noticed that `DateInput` sets an explicit background colour. This is because some mobile browsers set a grey background.
I think our other form fields should set their white background explicitly as well—at least to allow consumers to set a different colour and to prepare for dark mode later.

feat: Set explicit white background on text fields

---

packages/react/package.json
pnpm-lock.yaml

Our React package has a dependency on @babel/runtime, which wasn't defined. This PR fixes that

fix: Move @babel/runtime dev dependency to regular dependencies

---

storybook/src/docs/space.docs.mdx

I received feedback that the difference in the columns for the tables listing the values for Grid Space on various screen widths were confusing, and I agreed.
In a couple of iterations, I decided to use a step of 256 pixels for every column; some were 512 before. Compact Mode starts at 1088 and you can’t get down to 320 with steps of 512. And both tables’ columns needed to align.
The first cells in the table for compact mode have been merged to highlight that their values are the same. This required using an HTML table instead of Markdown.
I experimented with hiding the obscure columns of 2368 and 2624, but this is how the tokens work; I decided to remain complete.
Links to the pages: [current](https://designsystem.amsterdam/?path=/docs/docs-design-guidelines-space--docs), …

chore: Clarify spacious and compact values for Grid Space

---

packages/css/src/components/unordered-list/unordered-list.scss
packages/react/src/UnorderedList/UnorderedList.tsx
proprietary/tokens/src/components/ams/unordered-list.tokens.json
storybook/src/components/UnorderedList/UnorderedList.docs.mdx
storybook/src/components/UnorderedList/UnorderedList.stories.tsx

Do we want the use the same API as for Paragraph? So `size="small"`? Or a `small` boolean?

feat: Allow small text for unordered lists

---

packages/css/src/components/ordered-list/ordered-list.scss
packages/react/src/OrderedList/OrderedList.test.tsx
packages/react/src/OrderedList/OrderedList.tsx
packages/react/src/UnorderedList/UnorderedList.tsx
proprietary/tokens/src/components/ams/ordered-list.tokens.json
storybook/src/components/OrderedList/OrderedList.docs.mdx
storybook/src/components/OrderedList/OrderedList.stories.tsx

I've opted to use the same sizes as the paragraph because they can be used together.

feat: Allow small text for ordered lists

---

packages/react/src/UnorderedList/UnorderedList.test.tsx

I forgot this test in a previous PR

chore: Add test for `small` prop to UnorderedList

---

packages/css/src/components/link-list/link-list.scss
packages/css/src/components/paragraph/paragraph.scss
proprietary/tokens/src/components/ams/link-list.tokens.json
proprietary/tokens/src/components/ams/paragraph.tokens.json

The `medium` font size and line height are the default for Paragraph and Link List Link. The absence of a corresponding option for the `size` prop reflects this, as should the names of their design tokens.
This is how we do it in Ordered List and Unordered List as well.

fix!: Flatten token names for default text size and line height

---

packages/css/src/components/breadcrumb/breadcrumb.scss
packages/react/src/Breadcrumb/Breadcrumb.test.tsx
packages/react/src/Breadcrumb/Breadcrumb.tsx
packages/react/src/Breadcrumb/BreadcrumbLink.test.tsx
packages/react/src/Breadcrumb/BreadcrumbLink.tsx
packages/react/src/Breadcrumb/index.ts
proprietary/tokens/src/components/ams/breadcrumb.tokens.json
storybook/src/components/Breadcrumb/Breadcrumb.stories.tsx

A breadcrumb is a list of links. The ‘item’ level in between is implicit; the link is what matters. This change reflects that. Now the `href` prop is on a link, not an item.
Changes:
- The `Breadcrumb.Item` component has been renamed to `Breadcrumb.Link`
- Rest props and class names get applied to the `a` element instead of the `li`
- The `-item` fragment of the design tokens has been removed

feat!: Rename Breadcrumb Item to Link

---

packages/css/src/components/badge/badge.scss
packages/react/src/Badge/Badge.tsx
proprietary/tokens/src/components/ams/badge.tokens.json

Processed all badge colors from the Figma file, and remove dark-blue which is only used for the hover color of primary blue. This is why we need a semantic color layer.

feat!: Allow additional background colours for Badge and remove dark blue option

---

packages/react/README.md
storybook/config/storybook-overrides.css
storybook/src/components/Header/Header.docs.mdx
storybook/src/components/Icon/Icon.docs.mdx
storybook/src/components/MegaMenu/MegaMenu.docs.mdx
storybook/src/components/PageMenu/PageMenu.docs.mdx
storybook/src/components/TopTaskLink/TopTaskLink.docs.mdx
storybook/src/docs/color.docs.mdx
storybook/src/docs/components/StatusBadge.tsx
storybook/src/docs/components/status-badge.css
storybook/src/docs/icon-gallery.docs.mdx

Lorem ipsum texts have to be replaced with actual beta reasons or removed. Can you help me with that?

feat(internal): Indicate beta status for some components, patterns, and assets

---

packages/css/src/components/alert/README.md
packages/css/src/components/header/README.md
packages/css/src/components/header/header.scss
packages/react/src/Alert/Alert.test.tsx
packages/react/src/Alert/Alert.tsx
packages/react/src/Dialog/Dialog.test.tsx
packages/react/src/Dialog/Dialog.tsx
packages/react/src/Header/Header.test.tsx
packages/react/src/Header/Header.tsx
packages/react/src/TableOfContents/TableOfContentsLink.test.tsx
storybook/src/components/Alert/Alert.docs.mdx
storybook/src/components/Alert/Alert.stories.tsx
storybook/src/components/Card/Card.docs.mdx
storybook/src/components/Dialog/Dialog.stories.tsx
storybook/src/components/Header/Header.docs.mdx
storybook/src/components/Header/Header.stories.tsx
storybook/src/components/OrderedList/OrderedList.docs.mdx
storybook/src/components/UnorderedList/UnorderedList.docs.mdx
storybook/src/docs/typography.docs.mdx

Dialog: title -> heading (required)
Alert: title -> heading (optional)
Header: title -> siteName
And some missing tests

feat!: Rename title props for Alert, Header and Dialog and require it for Dialog

---

.eslintrc.json
packages/react/.eslintrc.json

/packages/react had its own eslint config, which isn't necessary.

chore: Simplify linting

---

packages/react/src/DateInput/DateInput.tsx
storybook/src/components/DateInput/DateInput.docs.mdx
storybook/src/components/DateInput/DateInput.stories.tsx

This allows the type of `datetime-local` for Date Inputs.
I copied the docs for disabled and invalid inputs from Text Input. We should probably extract this to some section on forms in general?

feat: Allow specifiying a time in a date input

---

packages/css/src/components/text-input/README.md
packages/react/src/DateInput/DateInput.test.tsx
packages/react/src/DateInput/DateInput.tsx
packages/react/src/TextInput/TextInput.test.tsx
packages/react/src/TextInput/TextInput.tsx
storybook/src/components/TextInput/TextInput.docs.mdx
storybook/src/components/TextInput/TextInput.stories.tsx

This allows the types of `password`, `email`, `url` and `phone` for Text Inputs.
I’ve added initial documentation to each type and to the existing examples for disabled and invalid inputs and placeholder text.

feat: Allow various types of text input

---

packages/css/src/components/accordion/accordion.scss

Text got centered because it is in a `<button>`.

fix: Start-align text in Accordion Button

---

packages/css/src/components/footer/README.md
packages/css/src/components/header/README.md

This follows up input from our design department that we hsould mark the Header and Footer as required for every page and every application because it plays such a big role in making all our websites recognizable as being from the City, which generates trust to use them.

chore: Document that the header and footer are required

---

packages/react/src/Avatar/Avatar.tsx
packages/react/src/ErrorMessage/ErrorMessage.tsx
packages/react/src/Header/Header.tsx
packages/react/src/IconButton/IconButton.tsx
packages/react/src/SearchField/SearchFieldButton.tsx
packages/react/src/SearchField/SearchFieldInput.tsx
packages/react/src/TopTaskLink/TopTaskLink.tsx
storybook/src/components/Avatar/Avatar.stories.tsx
storybook/src/components/Footer/Footer.stories.tsx

We're probably going to get rid of the VisuallyHidden React component, and just use it as a utility class. This PR prepares for that, and also fixes some invalid HTML in the Footer examples.
It also fixes an issue with the Avatar in Header story.

fix: Use visually hidden as utility class only

---

proprietary/tokens/src/brand/ams/text.compact.tokens.json
storybook/src/docs/typography.docs.mdx

The default text size (paragraphs on wide screens) is now 16 pixels instead of 18. This seems to be enough for applications. There is not much growing left now (from 14 to 16), we’ll have to evaluate that.
A next PR introduces compact spacing tokens. A second will include Amopis pages in Storybook. These three form an iteration to assess the values and change them where necessary. Thanks to the token layer, these changes aren’t breaking.

feat: Decrease text size in Compact Mode

---

proprietary/tokens/src/brand/ams/space.compact.tokens.json
storybook/src/docs/space.docs.mdx

This adds compact tokens for space. They follow the text sizes updated in #1306. All components will now have less inner space (paddings and gaps) in Compact Mode.

feat: Decrease space length in Compact Mode 

---

storybook/src/components/FieldSet/FieldSet.stories.tsx

What do we want to do with the error bar for FieldSets containing Fields? Should the error bar only be shown for the Field that has an input with an error (so `<Field invalid="true"`)? Or should it be shown for the entire FieldSet (so `<FieldSet invalid="true"`)?
Currently, the second option is shown.

chore: Use Fields in FieldSet docs

---

storybook/src/pages/amsterdam/ArticlePage/ArticlePage.docs.mdx
storybook/src/pages/amsterdam/FormPage/FormPage.docs.mdx
storybook/src/pages/amsterdam/FormPage/FormPage.stories.tsx
storybook/src/pages/amsterdam/FormPage/FormPage.tsx

Copied from the Signalen prototype, and:
- added a text area
- translated field names from Dutch to English
- added autocomplete values

chore: Add example of a form page

---

packages/css/src/components/heading/heading.scss
packages/react/src/Heading/Heading.test.tsx
packages/react/src/Heading/Heading.tsx

Heading CSS classnames now follow the lead of Heading tokens to include the word "level" to change the visual size, but not the position in the page hierarchy.

fix!: Change CSS classes for Heading level for consistency with token names

---

packages/react/src/Accordion/AccordionSection.tsx
packages/react/src/Card/CardLink.tsx
packages/react/src/Icon/Icon.tsx
packages/react/src/Link/Link.tsx
packages/react/src/Paragraph/Paragraph.tsx

Just checking things off my to do list…

chore: Rename otherProps to restProps for consistency

---

storybook/src/docs/typography.docs.mdx

I still made a copy paste error in #1389, apparently.

chore: Fix documentated values for Compact typography

---

packages/css/src/components/column/column.scss
packages/css/src/components/row/row.scss
packages/react/src/Column/Column.test.tsx
packages/react/src/Column/Column.tsx
packages/react/src/Row/Row.test.tsx
packages/react/src/Row/Row.tsx

The class names for the `gap` property of the `Row` and `Column` components didn’t meet NLDS naming convention. Now they do.
Because `medium` is the default value, I added tests for this class name. A subsequent PR will invert that test because it will move the default gap into the regular component class.

fix!: Include ‘gap-’ in class names for Row and Column gap

---

packages/react/package.json
packages/react/src/FieldSet/FieldSet.test.tsx
packages/react/src/FormErrorList/FormErrorList.test.tsx
packages/react/src/Image/Image.test.tsx
packages/react/src/PageMenu/PageMenu.test.tsx
packages/react/src/Row/Row.test.tsx
packages/react/src/Screen/Screen.test.tsx

This PR adds some missing tests.
Tests allow us to more easily see if we introduce regressions or breaking changes.
I ran the tests with coverage, to see which lines weren't covered yet. Some slightly more complicated tests aren't covered yet. 

chore: Add some missing tests

---

packages/react/src/Column/Column.tsx
packages/react/src/Row/Row.tsx
packages/react/src/common/layout.ts

To help developers select an allowed value of these props.
Makes them work faster and with less errors.
Uses const assertions (`as const`) on the list of string options to force its type not to be string[] but the array of values itself.
> An array has a numeric index signature, as it’s indexed by numbers (0, 1, 2, …), so we use typeof animals[number] to get a union type of all items in our array: 'cat' | 'dog' | 'mouse'.
– https://steveholgado.com/typescript-types-from-arrays/

chore: Support autocomplete for Row and Column gap and alignment

---

CONTRIBUTING.md
storybook/src/docs/developer-guide/getting-started.docs.mdx

Changes to the docs
1. The link to the CONTRIBUTING.md template didn't actually link to the template.
2. The install line didn't paste well in terminals
3. We now link to CONTRIBUTING.md from Storybook, so devs looking for these docs can more easily find them. 
By updating the docs

chore: Update getting started docs

---

packages/react/src/FormErrorList/FormErrorList.tsx

These come indirectly from `FormErrorListWithErrors`, so they don’t get automatically displayed in Storybook and IDEs.

chore: Document default values for Form Error List

---

packages/css/src/components/gap/README.md
packages/css/src/components/margin/README.md
storybook/src/foundation/design-tokens/border.docs.mdx
storybook/src/foundation/design-tokens/space.docs.mdx
storybook/src/styles/docs.css

I discovered that the space token previews would shrink with the window size. Seems logical because we use the actual tokens for their widt. On the other hand, we display these for their largest width only and the idea is to show the slope of the scale. That’s better done by expressing the largest values in rems, which don’t depend on the window size but do scale with text if people choose to do so.
The tables in the Space docs now show the full token names (`ams-space-xx`) instead of just the size (`xx`) – they are in the ‘Design Tokens’ section after all, and this matches how we displayed it for Borders. Then, having ‘Extra Small’ etc. as row headings didn’t add that much anymore so I merged those.
Some other changes too to make things easier to grasp. And ‘example’ instead of …

chore: Improve presentation of design token tables

---

packages/css/src/components/password-input/README.md
packages/css/src/components/text-input/README.md
packages/react/src/PasswordInput/PasswordInput.test.tsx
packages/react/src/PasswordInput/PasswordInput.tsx
storybook/src/components/TextInput/TextInput.docs.mdx

It removes unnecessary `autocapitalize` attributes. We used to set it for the PasswordInput, and we mentioned it for `input` types `url` and `email`. However, [`autocapitalize` doesn't do anything for these inputs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize#usage_notes). I tested this in Safari on iOS and Chrome, Edge and Samsung Internet on Android. 
The attribute is not necessary, and possibly confusing. 
By removing the attribute for PasswordInput, and updating the docs for TextInput. 
- Provide …

chore: Remove unnecessary 'autocapitalize' attribute

---

packages/css/src/components/checkbox/README.md
packages/css/src/components/page-menu/README.md
packages/css/src/components/search-field/README.md
packages/css/src/components/switch/README.md
storybook/src/components/Switch/Switch.docs.mdx
storybook/src/components/Switch/Switch.stories.tsx

It updates our guidelines for the Switch component.
We mentioned `aria-label` in the docs, which we advise against in other guidelines. The docs distinguished between a 'standalone' element and a form control, which is a little odd. Switch should always have a label I think, whether it's used in a form or not.
By removing references to `aria-label` and 'standalone component'.
- Mention any areas where additional review or …

chore: Update Switch docs

---

storybook/src/components/OrderedList/OrderedList.stories.tsx
storybook/src/components/TextArea/TextArea.stories.tsx
storybook/src/components/TextInput/TextInput.stories.tsx

It changes Text Input and Text Area to uncontrolled components in Storybook. 
Controlled components do not change automatically when interacting with them, you have to set an `onChange` handler for that. We didn't for Text Input and Text Area, which means you can't change the text. This PR fixes that.
By using `defaultValue` instead of `value`.

chore: Make Text Input and Text Area uncontrolled in stories

---

packages/css/src/components/dialog/README.md
packages/react/src/Dialog/Dialog.tsx
packages/react/src/Dialog/index.ts
storybook/src/components/Dialog/Dialog.docs.mdx
storybook/src/components/Dialog/Dialog.stories.tsx

This changes the Dialog close button from `type="submit"` to `type="button"`, and uses JS to close the Dialog.
We received [an issue noting that using the Dialog close button triggers a submit event](https://github.com/Amsterdam/design-system/issues/1546), which it shouldn't.
By changing the Dialog close button from `type="submit"` to `type="button"`, and using and exporting a JS function to close the nearest modal.
- JSDom doesn't fully support `dialog`, so this functionality isn't tested.

fix: Close Dialog without submit

---

packages/css/src/components/gap/README.md
packages/css/src/components/grid/README.md

It adds a guideline on both documentation pages not to use a Grid utility class on the Grid component.
Because we see this usage in the wild when it is not inteded.

chore: Document that Gap is not to be used on Grid

---

packages/css/src/components/field/field.scss
storybook/src/components/Checkbox/Checkbox.docs.mdx
storybook/src/components/Checkbox/Checkbox.stories.tsx
storybook/src/components/Radio/Radio.docs.mdx
storybook/src/components/Select/Select.docs.mdx
storybook/src/components/Select/Select.stories.tsx
storybook/src/components/TimeInput/TimeInput.docs.mdx
storybook/src/components/TimeInput/TimeInput.stories.tsx

It adds examples of using Checkbox, Select and Time Input in a Field or Field Set.
We added these examples for the other inputs already, these 3 were missing. 
By writing stories. 
This also adds `align-items: start;` to the Field CSS, to allow inputs to keep their intrinsic sizing. This doesn't seem to break anything, but it's probably smart to double check.

chore: Add Field (Set) examples to Checkbox, Select and Time Input

---

storybook/src/styles/overrides.css

It hides a transparent border that Storybook sets, which incorrectly shows in forced color mode. 
We want to support forced colors mode, this makes sure it also looks good in Storybook.
By giving the border a Canvas system color when in forced colors mode. 

chore: Do not show transparent border in Storybook in forced colors mode

---

packages/css/src/components/dialog/README.md
packages/react/src/Dialog/Dialog.tsx
packages/react/src/Dialog/index.ts
storybook/src/components/Dialog/Dialog.docs.mdx
storybook/src/components/Dialog/Dialog.stories.tsx

It adds the `closeDialog` and `openDialog` utility functions as methods to `Dialog`. 
Less exports and a more contained component.
Similar to how we do subcomponents, using `Object.assign`.

feat: Add utility functions as methods to Dialog

---

packages/css/src/components/avatar/avatar.scss
proprietary/tokens/src/components/ams/avatar.tokens.json

It adds a border to Avatar in forced colors mode.
Avatar relies on a background color to show its edges. In forced colors mode, the background color isn't visible.
This adds a border to Avatar in forced colors mode, and subtracts the width of the border from the padding, in order to keep the same dimensions. 

feat: Add border to Avatar in forced colors mode

---

storybook/src/components/OrderedList/OrderedList.docs.mdx
storybook/src/components/OrderedList/OrderedList.stories.tsx
storybook/src/components/UnorderedList/UnorderedList.stories.tsx

- Removes the ‘large’ option for the `size` of Ordered Lists in Storybook
- Displays the default ‘medium’ option for Unordered Lists
- Moves the ‘Small Text’ example of OL to the bottom to match UL
They didn’t reflect the actual implementation of the components.

chore: Fix options for text size examples of lists

---

packages/css/src/components/screen/screen.scss
storybook/config/preview.tsx
storybook/src/components/Grid/Grid.docs.mdx
storybook/src/components/Grid/Grid.stories.tsx
storybook/src/styles/docs.css

This shows light grey grid lines on the Grid examples to indicate the columns. It separates the concepts of columns and cells; cells are still pink. Examples are full-screen, which adds to the experience as well.
To position the background grid absolutely, I needed to add `position: relative` to the `Screen` component to let it provide a block formatting context. I think that is logical in general and can’t think of any regressions.
I’ve also edited the examples, e.g. giving them more consistent headers and less text.
Supersedes #1390.
To make it easier to grasp where the grid is.
Created a `BackgroundGrid` component that is shown behind the `Story`. We might export it later to use it …

chore: Visualise grid columns in the background of examples

---

packages/css/src/components/image-slider/README.md
packages/react/src/ImageSlider/ImageSlider.tsx

The guideline for a full-width Image Slider wasn’t accurate.
The resize handler was too eager.

chore: Improve Image Slider docs and resize handler

---

storybook/src/foundation/design-tokens/text.docs.mdx

See title.
Someone asked me about the growing of larger and smaller text sizes. It appeared this info had become incorrect. I also found the related sentences too unwieldy.
Rewritten it as compactly as I could.
I also changed the headings to sentence cases – apparently, we missed this file in #1565.

chore: Improve explanation of typographic scale

---

packages/react/package.json
packages/react/src/ImageSlider/ImageSlider.tsx
pnpm-lock.yaml

Lodash was not needed to debounce a resize event in ImageSlider.
- Uninstalled lodash
- Removed debounce from ImageSlider
The 200ms delay isn't needed. Tested on iOs where the bug occurred.

fix: Remove lodash

---

proprietary/tokens/README.md
proprietary/tokens/package.json

It documents the tokens package.
The fact that it was still empty appeared glaringly evident in the `package.json` of a consuming application (developers.amsterdam).
Wrote an initial version of it.

chore: Write README for tokens package

---

storybook/src/components/Label/Label.docs.mdx
storybook/src/components/Label/Label.stories.tsx

It was unclear how to use the optional property for `Label`. When adding the story I noticed using the `hint`property is also not documented, and when you use `hint` `optional` is not required. So I've added another story for hint.
Just stories for Label

feat: Optional and hint stories

---

packages/css/src/components/description-list/README.md
packages/css/src/components/description-list/description-list.scss
packages/react/src/DescriptionList/DescriptionList.test.tsx
packages/react/src/DescriptionList/DescriptionList.tsx
proprietary/tokens/src/components/ams/description-list.tokens.json
storybook/src/components/DescriptionList/DescriptionList.stories.tsx

- Adds an option to change the width of the column containing the term
- Changes the default behaviour to make the terms fit naturally
- Widens the gap between terms and columns; they were too close together
- Fixes toggling ‘inverse color’ for the ‘rich content’ example
- We received a request to support a different size than the one we offered
- Letting the size of content inform layout, like we now do, is often nicer
- Added a `termWidth` prop with three options `sm`, `md`, and `lg`.
- If the prop is `undefined`, the default behaviour applies
- Replaced the `gap` token with `column-gap` (breaking change) and started using `row-gap`
–

feat!: Support various column widths for Description List

---

packages/css/src/components/button/button.scss
packages/react/src/Button/Button.test.tsx
packages/react/src/Button/Button.tsx
proprietary/tokens/src/components/ams/button.tokens.json
storybook/src/components/Button/Button.docs.mdx
storybook/src/components/Button/Button.stories.tsx

Although the `iconPosition` enum is a bit more robust, we think an API with `iconBefore` and `iconOnly` booleans is friendlier.

feat!: Make API for icon in button friendlier

---

.github/workflows/feature-branch-cleanup.yml
.github/workflows/feature-branch-deploy.yml
.github/workflows/lint-test.yml
.github/workflows/publish.yml

It reverts using SHAs instead of version numbers in our GitHub workflows.
Using SHAs is a good idea ([see this for more info](https://devopsjournal.io/blog/2021/12/11/GitHub-Actions-Maturity-Levels)), but our organisation GitHub Action allowlist uses version number currently, which means the Actions using SHAs are blocked. We have to change the allowlist first before implementing this again.
Copy-pasting the old values back. I couldn't revert the files in their entirety, because I wanted to keep some of the changes. 

chore: Revert using SHAs in GitHub workflows

---

packages/react/src/DescriptionList/DescriptionList.tsx

Prevents rendering a class name of `ams-description-list--terms-width-undefined`.
The class is useless.
Added a condition.
–

fix: Don’t render a Description List class for an undefined value

---

.github/dependabot.yml

This groups Dependabot PRs. One group with all minor and patch dev dependency updates, one group with the same for prod dependency updates. 
Currently we use the Dependabot PRs to remind us that we have to update the deps. By grouping them, we can merge the PRs without having to do anything locally. No more `npm run update:minor`.
An added benefit is that we have separate PRs for dev and prod dependencies. Prod dependency updates should end up in our changelogs (because we change our published code, even if it is just the package.json). We currently don't do that, but this should make it easier. 
By using Dependabot groups.
Before submitting your pull request, please ensure you have …

chore: Group Dependabot PRs

---

packages/css/src/components/error-message/error-message.scss
packages/react/src/ErrorMessage/ErrorMessage.test.tsx
packages/react/src/ErrorMessage/ErrorMessage.tsx
proprietary/tokens/src/components/ams/error-message.tokens.json
storybook/src/components/ErrorMessage/ErrorMessage.docs.mdx
storybook/src/components/ErrorMessage/ErrorMessage.stories.tsx

Adds an Icon to Error Message
Error Message wasn't very prominent, and for colour-blind people or people using high contrast themes the Error Message wasn't very noticeable.
By adding a default icon and an `icon` prop.
The ticket specifies to add the Icon the same way we did for Radio. This isn't quite possible though, because we use the Icon component here, and it needs a Function instead of a ReactNode. We plan on changing this in the future though.

feat: Add Icon to Error Message

---

packages/css/src/components/file-input/file-input.scss

It lets File Input take up all available width.
Because all comparable inputs (Text Input, Password Input, Text Area, Select, Search Field) do so. And because not doing so [has been filed as an issue](https://github.com/Amsterdam/design-system/issues/1733).
Replaced `max-inline-size` with `inline-size` and added border box sizing to let sizing work with padding.

feat: Stretch File Input to full width to match other inputs

---

.github/workflows/publish.yml

It replaces a reference of a deprecated Release Please action to the current action. 
Because it's deprecated and will be removed in time. 
Replace the repo name
[Link to a thread of some of the issues this move created.](https://github.com/googleapis/release-please-action/issues/980)

chore: Use latest Release Please action in Publish workflow

---

packages/css/src/components/alert/alert.scss
packages/react/src/Alert/Alert.tsx
proprietary/tokens/src/components/ams/alert.tokens.json

1. Reverts #1757 where we added light background colours to Alert.
2. Adds and uses a token to make the background explicitly white.
1. Our branding department doesnt’t (yet?) accept these colours.
2. Because it was transparent, which may have side effects. It didn’t show because our Screen makes the background white, but a component must be fully responsible for its appearance. This also allows other NLDS communities to set a different background colour.
Changed tokens and classes.
- None

feat!: Make background of Alert white again

---

packages/css/src/components/overlap/overlap.scss

The Overlap CSS currently uses `grid-area: 1 / -1`. This is a shorthand for `grid-row-start: 1` `grid-column-start: -1`. 
This PR changes that to `grid-row`/`grid-column` `1 / -1`.
I don't think `grid-row-start: 1` `grid-column-start: -1` says what we want to say. We want all Overlap children to start on the first row / column and end on the last row / column. 
Functionally it doesn't matter, because there usually only is 1 row and 1 column. A user could put a `Grid.Cell` or something in Overlap though, which would create more rows / columns. 
By changing the CSS. 
Before submitting your pull request, please ensure you have done the following. Check each checkmark if you have done so or …

fix: Explicitly set row and column start and end in Overlap CSS

---

package.json
packages/css/package.json
packages/react/package.json
proprietary/assets/package.json
proprietary/react-icons/package.json
proprietary/tokens/package.json
storybook/package.json

Remove trailing slash from homepage field in package.jsons
This field is [shown on npm](https://www.npmjs.com/package/@amsterdam/design-system-tokens), and looks ugly imo. 
Find and replace

chore: Remove trailing slash from homepage field in package.jsons

---

documentation/publishing.md

Add documentation on how to update the changelogs when releasing.
We didn't describe this yet, and there are some gotcha's.
Typing

chore: Update publishing.md

---

storybook/src/components/Card/Card.docs.mdx

We received notice that this link to the Aspect Ratio no longer worked. That’s correct; it’s due to removing the component in the last release. I’ve checked all other links related to Aspect Ratio, and they are accurate.

fix: Fix link from Card docs to Aspect Ratio

---

.github/CODEOWNERS

It specifies that the design-system-maintainers group is code owner of all code in the repo.
Because that is what we want, but CODEOWNERS.md didn't specify this. 
By adding an asterix before `@Amsterdam/design-system-maintainers`.

chore: Fix CODEOWNERS.md

---

documentation/git.md

This updates the documentation to reflect our decision to only use `feat`, `fix`, and `chore` as the prefix for our branch names.

chore: Document updated prefixes for Git branches

---

packages/css/src/components/alert/alert.scss
packages/css/src/components/file-list/file-list.scss
packages/css/src/components/page-menu/page-menu.scss
packages/css/src/components/row/row.scss

Removes declarations of `flex-direction: row` as that’s the initial value.
I couldn’t quickly find a Stylelint rule that would automatically do this for the initial value of all non-inheriting properties.

chore: Remove CSS declarations that set the initial value for `flex-direction`

---

packages/react/src/MegaMenu/MegaMenu.tsx
storybook/src/components/Header/Header.docs.mdx
storybook/src/components/Icon/Icon.docs.mdx
storybook/src/components/MegaMenu/MegaMenu.docs.mdx
storybook/src/components/PageMenu/PageMenu.docs.mdx
storybook/src/components/TopTaskLink/TopTaskLink.docs.mdx
storybook/src/docs/components/StatusBadge.tsx
storybook/src/foundation/assets/icons.docs.mdx
storybook/src/foundation/design-tokens/colour.docs.mdx

The Header component is no longer in Beta.
The Mega Menu component is deprecated. I’ve updated the Status Badge component to allow customizing the status label and making it red for a deprecation.

feat: Remove Beta status from Header and deprecate Mega Menu

---

packages/css/src/components/avatar/avatar.scss
packages/react/src/Avatar/Avatar.tsx
storybook/src/components/Avatar/Avatar.docs.mdx

Restores the correct display of an Image in an Avatar.
The new default aspect ratio for the Image component (introduced in #1593) forces it to 16:9.
I’m resetting the aspect ratio for an `.ams-image` in an `.ams-avatar`. We don’t know its dimensions, and the user can’t easily provide them. We already ensured to show the center of the image; I’ve made that explicit in the docs.
I decided against using a clean HTML `img` element because we still want to apply the other base styles of our image component.
None.

fix(Avatar): Remove incorrect aspect ratio for image

---

packages/css/src/components/avatar/README.md
packages/css/src/components/avatar/avatar.scss
packages/react/src/Avatar/Avatar.test.tsx
packages/react/src/Avatar/Avatar.tsx
proprietary/tokens/src/components/ams/avatar.tokens.json
storybook/src/components/Avatar/Avatar.stories.tsx

This removes the possibility of making an Avatar blue (it is not interactive), red (it can’t communicate an error or an invalid interactive state), or neutral (we don’t have tokens for these options). The remaining colours are in the ‘highlight’ group that #1820 will introduce.
See above.
n/a
- n/a

feat(Avatar)!: Remove some colour options and make purple the default

---

packages/css/src/components/badge/README.md
packages/css/src/components/badge/badge.scss
packages/react/src/Badge/Badge.test.tsx
packages/react/src/Badge/Badge.tsx
proprietary/tokens/src/components/ams/badge.tokens.json
storybook/src/components/Badge/Badge.stories.tsx

This removes the possibility of making a Badge blue (it is not interactive) or neutral (we don’t have tokens for these options). The remaining colours are in the ‘highlight’ and ‘feedback’ groups that #1820 will introduce.
See above.
n/a
- n/a

feat(Badge)!: Remove some colour options

---

packages/css/src/components/tabs/tabs.scss

Prevent tabs buttons from shrinking
The button breaks text on small screen. At least in Chrome.
Single line that prevents shrinking

fix(Tabs): Prevent button text from wrapping

---

packages/css/src/components/tabs/tabs.scss
packages/react/src/Tabs/TabsButton.tsx

Disallows children of a `Tabs.Button` to become the target of pointer events.
To ensure the click event always returns the button as its target.
Through CSS.
- Adresses #1846.
- We can release this as a 0.14.1 hotfix. This is why it merges into a release branch.
- I considered adding a Storybook interaction test, but decided against it to keep the bugfix minimal. We should make a start with the subject, though.
- Test this by adding `onClick: (e: MouseEvent<HTMLElement>) => console.log('e.target:', e.target)` to the `args` of the Tabs …

fix(Tabs): Execute click handler on Button

---

packages/css/src/components/tabs/tabs.scss
storybook/src/components/Tabs/Tabs.docs.mdx
storybook/src/components/Tabs/Tabs.stories.tsx
storybook/src/components/shared/exampleContent.ts

Allows the content of a Tab Panel to scroll horizontally.
To prevent the Tabs from growing to contain its content, after which may overflow its container.
By adding `.ams-tabs__panel { overflow-x: auto; }` and an example.
- There has been some discussion on a composition of a Table in a Description List in a Tab Panel causing overflow. We concluded this is expected behaviour of CSS and that a responsive appearance of our table component may resolve this in the future. I recommended a local inline style to influence the local sizing behaviour …

feat(Tabs): Scroll wide content of a Tab Panel horizontally

---

packages/css/src/components/checkbox/checkbox.scss
packages/css/src/components/date-input/date-input.scss
packages/css/src/components/password-input/password-input.scss
packages/css/src/components/radio/radio.scss
packages/css/src/components/search-field/search-field.scss
packages/css/src/components/text-area/text-area.scss
packages/css/src/components/text-input/text-input.scss
packages/css/src/components/time-input/time-input.scss

See title. I checked that all component tokens in question now reference the correct brand colour token.

chore(docs): Remove obsolete comments about dark red colour token

---

packages/css/src/components/spotlight/README.md
packages/css/src/components/spotlight/spotlight.scss
packages/react/src/Spotlight/Spotlight.tsx
proprietary/tokens/src/components/ams/spotlight.tokens.json
storybook/src/components/Breakout/Breakout.stories.tsx
storybook/src/components/Spotlight/Spotlight.docs.mdx
storybook/src/components/Spotlight/Spotlight.stories.tsx

- Renames ‘green’ to ‘lime’ and ‘dark green’ to ‘green’ in the `color` prop of Spotlight.
- Updates documentation on text colour and fixes the example for an azure background.
To align with the updated colour names.
Typing.
- None

feat(Spotlight)!: Use updated color names for lime and green and remove purple as an explicit option

---

packages/css/src/components/badge/README.md
packages/css/src/components/badge/badge.scss
packages/react/src/Badge/Badge.tsx
proprietary/tokens/src/components/ams/badge.tokens.json
storybook/src/components/Badge/Badge.stories.tsx

- Renames ‘light blue’ to ‘azure’, ‘green’ to ‘lime’, and ‘dark green’ to ‘green’ in the `color` prop of Badge.
- Updates documentation on text colour.
To align with the updated colour names.
Typing.
- None

feat(Badge)!: Use updated color names for azure and lime

---

packages/css/src/components/gap/README.md
packages/css/src/components/margin/README.md
storybook/src/components/CharacterCount/CharacterCount.docs.mdx
storybook/src/docs/developer-guide/interactivity.docs.mdx
storybook/src/foundation/design-tokens/aspect-ratio.docs.mdx
storybook/src/foundation/design-tokens/border.docs.mdx
storybook/src/foundation/design-tokens/colour.docs.mdx
storybook/src/foundation/design-tokens/cursor.docs.mdx
storybook/src/foundation/design-tokens/space.docs.mdx
storybook/src/styles/docs.css

- `ams.token.name` → `var(--ams-token-name)`; easier fo people to copy and paste
- Token name → CSS variable
- Color name → Colour
- Explicitly align Markdown table columns
- Dashed grey border → pink background for better visibility and consistency with Grid, Row, etc.
- Skipped `text.docs.md` because it gets deleted in PR 1845.

chore(docs): Make token tables consistent

---

packages/css/src/components/avatar/README.md
packages/css/src/components/avatar/avatar.scss
packages/react/src/Avatar/Avatar.tsx
proprietary/tokens/src/components/ams/avatar.tokens.json

- Renames ‘light blue’ to ‘azure’, ‘green’ to ‘lime’, and ‘dark green’ to ‘green’ in the `color` prop of Avatar.
- Updates documentation on text colour.
To align with the updated colour names.
Typing.
- None

feat(Avatar)!: Use updated color names for azure, lime and green 

---

packages/css/src/components/accordion/accordion.scss
packages/css/src/components/badge/badge.scss
packages/css/src/components/breadcrumb/breadcrumb.scss
packages/css/src/components/button/button.scss
packages/css/src/components/character-count/character-count.scss
packages/css/src/components/checkbox/checkbox.scss
packages/css/src/components/description-list/description-list.scss
packages/css/src/components/error-message/error-message.scss
packages/css/src/components/figure/figure.scss
packages/css/src/components/file-list/file-list.scss
packages/css/src/components/link-list/link-list.scss
packages/css/src/components/link/link.scss
packages/css/src/components/ordered-list/ordered-list.scss
packages/css/src/components/paragraph/paragraph.scss
packages/css/src/components/radio/radio.scss
packages/css/src/components/table-of-contents/table-of-contents.scss
packages/css/src/components/top-task-link/top-task-link.scss
packages/css/src/components/unordered-list/unordered-list.scss

Implements hyphenation for a bunch of components where it seemed missing
To make more types of text fit their containers more easily.
By including out hyphenation mixin in CSS.
- None

feat: Add missing hyphenation behaviour to all text components

---

package.json

Configures a breaking change of pnpm 10:
By default no dependency is allowed to run lifecycle scripts during installation ([PR](https://github.com/pnpm/pnpm/pull/8897)).
To slightly increase security (“This only makes one attack vector harder” – [maintainer](https://github.com/pnpm/pnpm/pull/8897#issuecomment-2558124547)).
1. Ran `pnpm approve-builds`, select no packages, save.
2. Tested a clean reinstall.
- More info: https://socket.dev/blog/pnpm-10-0-0-blocks-lifecycle-scripts-by-default

chore(deps): Block lifecycle scripts of dependencies during installation

---

packages/react/src/Tabs/Tabs.test.tsx
packages/react/src/Tabs/Tabs.tsx
storybook/src/components/Tabs/Tabs.stories.tsx

This renames the `onChange` prop to `onTabChange`.
`onChange` seemed to conflict with the native React `onChange` prop. 
See also [this issue](https://github.com/Amsterdam/design-system/issues/1846).
- Do we also want to change `tabId` to `string` now? Or should that be a separate PR?

fix(Tabs)!: Rename onChange to onTabChange

---

packages/css/src/components/icon/icon.scss
proprietary/tokens/src/components/ams/icon.tokens.json

This lets the browser use baseline alignment to align an icon with text. We make the icon adhere to that feature by adding a zero-width space to its `::after` pseudo-element.
It seems more idiomatic to use the browser’s baseline alignment feature to align an icon to accompanying text. We still need to apply typography to the icon, but that’s logical: we treat an icon as a typographic element. Stretching the icon and the pseudo-element and using a width of `1em` are more examples of using what CSS offers us. We don’t need to multiply font size with line height anymore, and we don’t need to manually size the SVG while we were already sizing its container.
See above.
Before submitting your …

feat(Icon): Add invisble text content to simplify baseline alignment

---

storybook/src/components/Header/Header.stories.tsx
storybook/src/pages/amsterdam/common/AppHeader.tsx

This shows ‘Menu’ instead of ‘Alle onderwerpen’ in the menu button in the Header of our example pages.
We found that ‘Alle onderwerpen’ is too long to make the Header fit on one line in narrow windows. It’s also not a usual term for a menu.
‘Alle onderwerpen’ is still in the mega menu to explain how we structured our menu. And I kept it visible in our example for a custom menu button label.
n/a
- n/a

chore(docs): Use ‘Menu’ as the menu button label in example pages 

---

storybook/src/components/Footer/Footer.stories.tsx

This removes the Heading level 1 from our Footer examples. It also changes a `section` to a `div`, [a section should not be used for styling purposes only](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#usage_notes).
According to [these docs](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/), there should only be 1 `h1` on the page. This means our docs were incorrect. 
Removed the heading, changed the tag. 

chore(Footer): Fix heading hierarchy

---

packages/react/src/Header/Header.tsx

Checks if Header has a mega menu and only then calls `useIsAfterBreakpoint`.
`useIsAfterBreakpoint` uses `matchMedia`, which you have to mock in unit tests. If we don't do this check, users that do not have a mega menu still have to mock matchMedia in their tests, although it isn't necessary. 
Add a condition.

fix(Header): Only use matchMedia when there is a mega menu

---

packages/react/package.json
packages/react/rollup.config.mjs
packages/react/tsconfig.json

Generate separate React components and their corresponding types alongside the barrel files we already generate.
Only having barrel files isn't always flexible enough. See also [this PR](https://github.com/Amsterdam/design-system/pull/1925) and [this ticket](https://gemeente-amsterdam.atlassian.net/browse/DES-1223). 
By running the `tsc` command and not messing with the generated types. 
I've compared the generated files before and after this change. They're identical, with the exception of some ordering in `index.d.ts`, which shouldn't be a problem.
I've also checked if `build:watch` and HMR in Storybook still works as aspected, that seems to be the case. 
Before submitting your pull …

feat: Build separate React components alongside barrel file

---

packages/css/src/components/action-group/action-group.scss

It aligns the items of an ActionGroup to center instead of baseline. 
Baseline alignment caused [an issue](https://github.com/Amsterdam/design-system/issues/1918) when used in combination with our Icon component. 
Changed `baseline` to `center`. Checked what it looked like in the case provided and in our other stories.

fix(Action Group): Align content to center instead of baseline

---

packages/css/src/components/aspect-ratio/README.md
packages/css/src/components/aspect-ratio/aspect-ratio.scss
packages/css/src/components/gap/README.md
packages/css/src/components/gap/gap.scss
packages/css/src/components/margin/README.md
packages/css/src/components/margin/margin.scss
packages/react/src/Image/generateAspectRatioClass.ts
storybook/src/components/Breakout/Breakout.stories.tsx
storybook/src/components/Checkbox/Checkbox.stories.tsx
storybook/src/components/DescriptionList/DescriptionList.stories.tsx
storybook/src/components/Dialog/Dialog.docs.mdx
storybook/src/components/FieldSet/FieldSet.stories.tsx
storybook/src/components/Footer/Footer.stories.tsx
storybook/src/components/Header/Header.stories.tsx
storybook/src/components/Radio/Radio.stories.tsx
storybook/src/components/Tabs/Tabs.stories.tsx
storybook/src/pages/amsterdam/ArticlePage/ArticleBody.tsx
storybook/src/pages/amsterdam/ArticlePage/ArticleHeader.tsx
storybook/src/pages/amsterdam/FormPage/FormPage.tsx
storybook/src/pages/amsterdam/HomePage/HomeSpotlight.tsx
storybook/src/pages/amsterdam/common/AppHeader.tsx
storybook/src/utils/Gap/Gap.stories.tsx
storybook/src/utils/Margin/Margin.stories.tsx

This removes one of the double dashes in the class names `ams-aspect-ratio-*`, `ams-gap-*` and `ams-mb-*`.
It also fixes the display of the examples for gap and margin; they were still using tokens that we removed in #1910.
We concluded BEM doesn’t apply to utility classes.
I think you know how.
- n/a

feat(Aspect Ratio, Gap, Margin)!: Use single dash in utility classes

---

packages/css/src/components/gap/gap.scss

Replaces an attribute selector shaped `[attr|=value]`.
Because we expected it to select `<div class="foo ams-gap">`, but it doesn’t. This utility class should always work, irrespective of other classes on the element. 
Changing it to `[class*="ams-gap-"]` is an option, but maybe we should just add `display: grid` to five possible class names rather than trying to be smart.
n/a
- n/a

fix(Gap): Make sure grid display is always set

---

packages/css/src/components/screen/README.md
storybook/src/components/Grid/Grid.stories.tsx
storybook/src/components/Screen/Screen.docs.mdx
storybook/src/components/Screen/Screen.stories.tsx
storybook/src/styles/docs.css
storybook/src/utils/AspectRatio/AspectRatio.stories.tsx

Removes padding from our `ams-docs-item` class that we use in Storybook to show a pink box. The padding got added to our aspect ratio examples too, distorting their actual aspect ratio.
The padding was needed for examples where the docs item contained text. We have had quite a few of those, but only two instances were left in the examples for Screen, that weren’t so strong anyway.
So we can decide not to use text in a docs item anymore. I removed typography and updated the Screen examples to restore some of the message that the removed text had.
I also made the sizing of docs item more consistent: just inline size and block size, no more padding and flex basis in the mix.
We use the …

chore(docs): Correct indications of aspect ratio

---

packages/css/src/components/visually-hidden/visually-hidden.scss

It prevents users from copying visually hidden text. There don't seem to be any screenreader issues with this, they still seem to read the text. 
When copying text, it's a little surprising that you get text you can't see.
`user-select: none;`

feat: Do not copy visually hidden text

---

packages/css/src/components/icon/icon.scss

Center align SVG in Icon.
This did not always happen. It worked for Icon in a Button and in Link List, but not in a Pagination link.
We're not sure why, but `align-items: center` fixes the problem and makes the alignment more explicit. 
Adding a CSS rule. 

fix(Icon): Center align SVG

---

packages/react/package.json
pnpm-lock.yaml

I checked if we had major upgrades available, and this was the only one besides React 19, and it’s not breaking for us.

chore(dev-deps): Update rollup-plugin-node-externals to v8.0.0

---

packages/react/src/PageHeader/PageHeader.tsx

It removes passing `restprops` to the menu button.
A user mentioned this was a problem. It was probably a copy-paste mistake, the menu button shouldn't receive the `restprops`. 
Delete a line

fix(PageHeader): Remove restprops from menu button

---

packages/react/src/Accordion/Accordion.test.tsx
packages/react/src/Accordion/Accordion.tsx
packages/react/src/Tabs/Tabs.test.tsx
packages/react/src/Tabs/TabsList.tsx

It removes disabled buttons from the Tabs focusable elements selector, and it adds a specific selector for Accordion. It also adds unit tests to Accordion and Tabs to check if this functionality keeps working.
When adding a disabled Tabs button, the keyboard focus could not pass it. When adding a regular button to an Accordion Section, it would erroneously receive focus when using the arrow keys. 
Using the class name as selectors, and adding `:not([disabled])`

fix(Accordion, Tabs): Only allow keyboard focus on relevant buttons

---

packages/react/src/Tabs/Tabs.tsx

We received [an issue](https://github.com/Amsterdam/design-system/issues/2008) that the active tab state was lost after a rerender. This fixes that issue. 
Bugs are bad
`allTabIds` was calculated in a `useMemo` with `children` in its dependency array. The reference to children changes every rerender, so `allTabIds` was calculated every rerender (making `useMemo` kind of useless here). This removes `children` from the dependency array, which means `allTabIds` is only calculated on the first render. 

fix(Tabs): Do not lose active tab state after rerender

---

packages/react/src/Tabs/TabsButton.test.tsx
packages/react/src/Tabs/TabsButton.tsx
storybook/src/components/Tabs/Tabs.docs.mdx
storybook/src/components/Tabs/Tabs.stories.tsx

Allows users to prevent Tabs from switching to different panel.
This was requested in [this issue](https://github.com/Amsterdam/design-system/issues/1948). It's helpful to keep users from switching tabs if that means they lose form data for example.
Do not fire `updateTab` if `event.defaultPrevented` is true.

feat(Tabs): Allow preventing Tabs from switching to different panel

---

packages/css/src/components/image/image.scss

It sets the Image inline size to 100%.
Using `fit-content` [caused issues](https://gemeente-amsterdam.atlassian.net/browse/DES-1277) when using multiple images for different screen widths and resizing. It also caused layout shifts, because the content size of an image that hasn't loaded yet is 0.
Change `inline-size` to 100% and removing `max-inline-size`. I've tested this in our prototypes, where both issues did not occur any more. 
- Add a link to the specific story in the feature …

fix(Image): Set inline size to 100%

---

packages-proprietary/tokens/src/components/ams/ordered-list.tokens.json
packages-proprietary/tokens/src/components/ams/unordered-list.tokens.json

Sets a small gap between items of an Ordered or Unordered List, instead of a medium one.
The gap was too large. It had been designed as such to accommodate list items with several lines of content, but they occur less in practice and list items with short content suffer.
The gap between Link List Items is small as well.
We might consider two variations of lists to support both longer and shorter content. We could also instruct to use a Paragraph for long content in a List Item, and add the extra whitespace to that.
Changed token values.
- …

feat(Ordered List, Unordered List): Use small gap between items instead of medium

---

packages-proprietary/tokens/src/brand/ams/color.tokens.json
storybook/config/manager.js

Replaces a stray #000000 with #181818 in our colour tokens.
Updates two instances in our Storybook config as well.
We don’t use pure black anymore.
n/a
- n/a

fix: Correct shade of black for interactive contrast colour

---

packages-proprietary/tokens/src/components/ams/ordered-list.tokens.json
packages-proprietary/tokens/src/components/ams/unordered-list.tokens.json
packages/css/src/components/ordered-list/ordered-list.scss
packages/css/src/components/unordered-list/unordered-list.scss

Adds a bit of whitespace below a nested list, unless it is in the last item of its parent.
To better indicate that the nested list belongs to its parent and not the next sibling of its parent.
- I’ve used child combinators and ‘not last child’ in CSS. This might fail with invisble nodes. The `:has` selector might help but isn’t widely supported yet.
- I’ve omitted the `li` type selector on purpose. The element in between should be one, but if it’s something else, we still want this effect. And it prevents increasing specificity.
- n/a

feat(Ordered List, Unordered List): Visually group nested list with parent item

---

packages-proprietary/tokens/src/components/ams/checkbox.tokens.json
packages-proprietary/tokens/src/components/ams/radio.tokens.json

Lets the square shape of Checkbox, and the circle shape of Radio, scale with text. See #2127. Note that this makes the border width slightly less than `2px` on narrow screens.
They currently have a fixed size, which doesn’t work well with our responsive typography and in Compact Mode.
Use font size tokens for the width of the icon container.
- n/a

feat(Checkbox, Radio): Make the size of controls fluid like text

---

packages/css/src/components/switch/switch.scss

Removes phantom whitespace below a Switch.
It’s unintentional and may introduce layout issues.
By adding the good old `vertical-align: middle` to `.ams-switch__label`.
Our robot friends explain:
> `vertical-align: middle` fixes the phantom whitespace because `.ams-switch__label` is `inline-block` by default, and its baseline aligns with the baseline of surrounding inline content. The pseudo-element inside is a block, but the label itself sits on the baseline, leaving extra space below (for descenders).
>
> By setting `vertical-align: middle`, the label aligns to the middle of the line box, removing the extra space below and making the switch height match the visual content. This centers …

fix(Switch): Remove phantom whitespace below

---

packages/css/src/components/date-input/date-input.scss
packages/css/src/components/password-input/password-input.scss
packages/css/src/components/search-field/search-field.scss
packages/css/src/components/select/select.scss
packages/css/src/components/text-area/text-area.scss
packages/css/src/components/text-input/text-input.scss
packages/css/src/components/time-input/time-input.scss

It fixes 2 visual bugs:
- The invalid hover styling had a black inset box shadow for several inputs, instead of a dark red one
- The invalid styling 'beat' the disabled styling, which is not what we want
Bugs are bad
Got rid of some of the nesting, and added `:not(:disabled)` in several spots

fix: Use correct styling for disabled and / or invalid inputs

---

packages-proprietary/tokens/src/components/ams/field-set.tokens.json

It makes the space below the legend in a Field Set smaller.
The `gap` in a Field was already small, but we set a medium space below the legend in a Field Set. This was a little inconsistent, and looked off with the smaller font sizes we now use.
Change `m` to `s`.

feat(Field Set): Make space below legend smaller
